<?
$PERM["iblock_section_admin.php"]["6"]="R";
$PERM["iblock_section_admin.php"]["7"]="R";
$PERM["index.php"]["6"]="R";
$PERM["index.php"]["7"]="R";
$PERM["iblock_element_edit.php"]["6"]="R";
$PERM["iblock_element_edit.php"]["7"]="R";
$PERM["iblock_element_admin.php"]["6"]="R";
$PERM["iblock_element_admin.php"]["7"]="R";
?>